version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing the npm modules for the Angular project...
      - npm install
      - ECR_REPO=415353467794.dkr.ecr.us-east-2.amazonaws.com
      - echo Logging in to Docker Hub...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 415353467794.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build the Angular app...
      - npm run build-prod
  post_build:
    commands:
      #- aws s3 sync ./dist/rmm-web s3://om-order-app --acl 'public-read' --delete
      - docker push $ECR_REPO/om-order-web:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "om-service-container" "$ECR_REPO/om-order-web:latest" > imagedefinitions.json
      - ls -la
artifacts:
  files: imagedefinitions.json
