version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing the npm modules for the Angular project...
      - npm install
  build:
    commands:
      - echo Build the Angular app...
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync ./dist/rh-web s3://om-order-app --acl 'public-read' --delete