version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing the npm modules for the Angular project...
      - npm install
  build:
    commands:
      - echo Build the Angular app...
      - npm run build-prod
  post_build:
    commands:
      #- aws s3 sync ./dist/rh-web s3://om-order-app --acl 'public-read' --delete
  post_build:
    commands:
      - docker push $ECR_REPO/om-order-web:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "om-service-container" "$ECR_REPO/om-order-web:latest" > imagedefinitions.json
      - ls -la
artifacts:
  files: imagedefinitions.json
